# Ejercicio 1 - Importación de datos con Pandas

Combinar datos de ventas (CSV), clientes (JSON) e inventario (Excel) para un análisis de comercio electrónico.

In [1]:
import pandas as pd

# 1. Cargar los datos de ventas desde el archivo CSV
ventas = pd.read_csv('ventas.csv')
print("Vista previa de VENTAS:")
ventas.head()

Vista previa de VENTAS:

,id_venta,fecha,id_cliente,producto,cantidad,precio_unitario,total
0,1,2024-02-10,5,Monitor,2,120.23,240.46
1,2,2024-02-27,2,Impresora,1,33.54,33.54
2,3,2024-04-17,9,Notebook,5,167.08,835.40
3,4,2024-09-23,4,Tablet,5,229.77,1148.85
4,5,2024-01-15,7,Webcam,3,132.83,398.49

In [2]:
# 2. Cargar los datos de clientes desde el archivo JSON
clientes = pd.read_json('clientes.json')
print("Cantidad total de clientes:", len(clientes))
clientes.head()

Cantidad total de clientes: 10

   id_cliente       nombre                 email        ciudad fecha_registro
0           1    Ana Gomez    ana.gomez@mail.com       Ushuaia     2023-09-08
1           2   Luis Perez   luis.perez@mail.com       Cordoba     2023-11-16
2           3   Marta Diaz   marta.diaz@mail.com  Buenos Aires     2023-09-05
3           4  Carlos Ruiz  carlos.ruiz@mail.com       Mendoza     2023-10-16
4           5  Sofia Lopez  sofia.lopez@mail.com  Buenos Aires     2023-08-26

In [3]:
# 3. Cargar los datos de inventario desde la hoja de cálculo Excel
inventario = pd.read_excel('inventario.xlsx')
promedio_stock = inventario['stock'].mean()
print("Promedio de stock disponible:", round(promedio_stock, 2))
inventario.head()

Promedio de stock disponible: 64.62

   id_producto     producto    categoria  stock  precio
0            1     Notebook  Perifericos     86  642.47
1            2        Mouse     Hardware     63  161.36
2            3      Teclado  Perifericos    114  120.74
3            4      Monitor     Hardware     71  375.48
4            5  Auriculares     Hardware    113  648.34

### Combinar los datos en una sola estructura

Unimos `ventas` con `clientes` (por `id_cliente`) para tener toda la información en un solo DataFrame.

In [4]:
# Combinar ventas + clientes en una sola tabla
ventas_completas = ventas.merge(clientes, on='id_cliente', how='left')
ventas_completas.head()

,id_venta,fecha,id_cliente,producto,cantidad,precio_unitario,total,nombre,email,ciudad,fecha_registro
0,1,2024-02-10,5,Monitor,2,120.23,240.46,Sofia Lopez,sofia.lopez@mail.com,Buenos Aires,2023-08-26
1,2,2024-02-27,2,Impresora,1,33.54,33.54,Luis Perez,luis.perez@mail.com,Cordoba,2023-11-16
2,3,2024-04-17,9,Notebook,5,167.08,835.40,Julia Castro,julia.castro@mail.com,Rosario,2023-12-02
3,4,2024-09-23,4,Tablet,5,229.77,1148.85,Carlos Ruiz,carlos.ruiz@mail.com,Mendoza,2023-10-16
4,5,2024-01-15,7,Webcam,3,132.83,398.49,Elena Vidal,elena.vidal@mail.com,Ushuaia,2023-11-14

In [5]:
# Resumen general
print("Cantidad de ventas registradas:", len(ventas))
print("Cantidad de clientes:", len(clientes))
print("Cantidad de productos en inventario:", len(inventario))
print("Promedio de stock:", round(promedio_stock, 2))

Cantidad de ventas registradas: 30
Cantidad de clientes: 10
Cantidad de productos en inventario: 8
Promedio de stock: 64.62